name: Update demo

on:
  push:
    branches:
      - main

jobs:
  update_demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout datasette-plugin
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout datasette-plugin-template-demo
      uses: actions/checkout@v2
      with:
        repository: simonw/datasette-plugin-template-demo
        path: datasette-plugin-template-demo-current
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install cookiecutter
    - name: Build demo from template
      run: |-
        cat main/input-for-demo.txt | cookiecutter main
        find datasette-plugin-template-demo
    - name: Push to git
      env:
        PERSONAL_ACCESS_TOKEN_FOR_PUSH: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
      run: |-
        # Move the .git folder across
        mv datasette-plugin-template-demo-current/.git datasette-plugin-template-demo
        # Commit and push the changes
        cd datasette-plugin-template-demo
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A .
        git remote set-url origin https://simonw:$PERSONAL_ACCESS_TOKEN_FOR_PUSH@github.com/simonw/datasette-plugin-template-demo.git
        git commit -m "Latest demo: ${GITHUB_SHA}" || exit 0
        git push
